### PR TITLE
Updated ReadMe with well structured explanation and in an organized manner!

### PR DESCRIPTION
**Pull request by Developer-piyush**
### Description
I have updated both readme(english, chinese) with well structured explanation and in an organized manner, this will create a good impact on all the users/investors to see repository.
First impression is last impression!

### Notes
Updated whole readme!

### BTC/BGL PR reward address
Ethereum address: 0x376AD3f8Ea767E2913E60E49C6C5DC812f86Fc16
Bitcoin Network(BTC): 1PnCcHUFEwRaJy7936JuZU4kFjT33xK3bq

I prefer ethereum, plzz do send ethereum stablecoin if possible!

### CODE REVIEW

**Comment by Developer-piyush** [comment]
Updated both English as well Chinese  Readme:
English: https://github.com/Developer-piyush/bitgesell/blob/master/README.md
Chinese: https://github.com/Developer-piyush/bitgesell/blob/master/README-zh.md

As we all can see official readme has lot of bugs and errors without any styling and explanations, this may create a negative impressions on visitors as well as investors so i dedicated some time to not only add styling but also updated whole content with clear explainations!

My wallet address:  0x376AD3f8Ea767E2913E60E49C6C5DC812f86Fc16

THANK YOU

**Comment by Developer-piyush** [comment]
**Any update on this PR, waiting desperately** :)

**Comment by Developer-piyush** [comment]
It looks like no one is interested in my PR! ;(

**Comment by wu-emma** [comment]
Hi Piyush, I looked through you PR it's not related to functional changes, described in task. 
I'm ready to pay 100 USDT for that (would make an exception).
@van-orton take a look and merge if it looks ok.

**Comment by Developer-piyush** [comment]
> Hi Piyush, I looked through you PR it's not related to functional changes, described in task.
> I'm ready to pay 100 USDT for that (would make an exception).
> @van-orton take a look and merge if it looks ok.

thank you so much @wu-emma

**Comment by wu-emma** [comment]
txid is 0xfb5ef06131f8197085087736d11df3da324ce41e57b7a59a1fdce70adad8991b

**Comment by Developer-piyush** [comment]
> txid is 0xfb5ef06131f8197085087736d11df3da324ce41e57b7a59a1fdce70adad8991b

Thank you so much! @wu-emma  i will contribute more to the project soon!

**Comment by Developer-piyush** [comment]
> txid is 0xfb5ef06131f8197085087736d11df3da324ce41e57b7a59a1fdce70adad8991b

I think you quoted wrong transaction hash by mistake, this is the one which you sent to antony!
Thank you

**Pull request merged**
