### PR TITLE
Debian package

### PR DESCRIPTION
**Pull request by vporton**
### Description
Issue https://github.com/wu-emma/bitgesell/issues/9 _Create Ubuntu/Debian Package Script So That Deb Won't Require Libdb_.

### Notes
I added not only bdb-4.8 required by the issue but also:
* boost
* libevent
* miniupnpc

It was necessary to make it work on both Ubuntu 18.04 and 20.04.1.

I made it to build inside a Docker with 18.04 inside. _That's the only way to make it work on 18.04._

I worked about 29 hours and tried really many variants (especially because of multiple bugs I encountered) to make it work. You can see the long commit history for (some of!) my tries.

Please increase the reward sum: I integrated four packages instead of one and that was in a really hard path of fighting with bugs, I made build inside Docker instead of just build.

I excluded GUI functionality to make things simpler and decrease installation size. If you want, I can add it on your request.

I didn't test on anything else than Ubuntu, because it was explicitly not in the task specification. If you want me to test more, add additional funding.

P.S. I didn't accomplish the request to put it to `tools/` directory, because it is hardcore against standards and would require a silly hack. But if you insist, I will do.

### CODE REVIEW

**Comment by van-orton** [comment]
Testing build of the package, unfortunately cannot get it to work, getting the following error:

```
dpkg-source: info: extracting bitgesell in bitgesell-0.1.2
dpkg-source: info: unpacking bitgesell_0.1.2.tar.xz
 dpkg-buildpackage -rfakeroot -us -uc -ui -b
dpkg-buildpackage: info: source package bitgesell
dpkg-buildpackage: info: source version 0.1.2
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Victor Porton <porton@narrod.ru>
 dpkg-source --before-build bitgesell-0.1.2
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --with autoreconf
   dh_clean
 debian/rules build
cd distrib/boost_1_74_0 && \
	./bootstrap.sh CC=gcc-8 CXX=g++-8 --prefix=/home/user/build/bitgesell-0.1.2/distrib/tmp/libboost && \
	./b2 install
./bootstrap.sh: 1: ./bootstrap.sh: ./tools/build/src/engine/build.sh: not found
Building Boost.Build engine with toolset ... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
debian/rules:19: recipe for target 'boost' failed
make: *** [boost] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -b failed
```

looks like boost sources in distrib are missing something, checking
(probably https://github.com/boostorg/build.git submodule is missing)

**Comment by vporton** [comment]
It is because of wrong `.gitignore`. I've corrected it. Please test again.

**Comment by van-orton** [comment]
boost is now getting built.
- for the libdb: dist directory should be included (configure script is located in there);
- for the libevent: autogen.sh should be run (as it will create configure script, which does not exist before that step);

- now at last lib in distrib folder
```
cd distrib/miniupnpc-2.1.20200928 && \
	make && \
	make DESTDIR=/home/user/build/bitgesell-0.1.2/distrib/tmp/miniupnpc install
make[1]: Entering directory '/home/user/build/bitgesell-0.1.2/distrib/miniupnpc-2.1.20200928'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/user/build/bitgesell-0.1.2/distrib/miniupnpc-2.1.20200928'
debian/rules:43: recipe for target 'miniupnpc' failed
make: *** [miniupnpc] Error 2
```
looks like just Makefile is missing from original repo.

can you please add/check the changes to those libs too?

**Comment by vporton** [comment]
I made it to download `distrib/` files from network instead of distributing them. Now it works. I also squashed all commits into one.

**Review by van-orton — COMMENTED** [review]
I've managed to get .deb package built. And it is indeed working on clean Ubuntu installation without and dependencies. Probably we won't merge this PR directly, but will think how to group it properly (as distrib folder is pretty large).
Nonetheless, I think that work is done, and will tell write Emma to get the bounty paid.
Thanks Victor! @vporton

**Comment by van-orton** [comment]
Oops, you've made it to grab sources from repositories. That's much better and cleaner! Give me an hour to check and then we can merge it probably.

**Comment by vporton** [comment]
> I've managed to get .deb package built. And it is indeed working on clean Ubuntu installation without and dependencies. Probably we won't merge this PR directly, but will think how to group it properly (as distrib folder is pretty large).
> Nonetheless, I think that work is done, and will tell write Emma to get the bounty paid.
> Thanks Victor! @vporton

I removed the `distrib/` folder. Now the distrib packages are downloaded from network when the package is built.

I remind that I did several times more work than originally anticipated (see above). Please increase the payout sum.

**Comment by wu-emma** [comment]
Hi @vporton the payment has been done (increased amount to $500), https://etherscan.io/tx/0xa52486ac6ddffb15e5dd3589562cbe4a96d02ad2412427dadcad2d6edaffd2a0
The metamask bugged somehow, and the bounty remained opened, please check if you have any kind of button to mark the bounty as closed? Thanks and let's continue to work, will invite you to new bounties!

**Comment by vporton** [comment]
Thank you.

No, I also have no way to mark it as closed.

**Comment by van-orton** [comment]
Merging (would apply some typos fix immediately afterwards)

**Pull request merged**
