### PR TITLE
Remove sign message feature from the UI

### PR DESCRIPTION
**Pull request by naftalimurgor**
### Description
This PR gracefully removes the feature of signing a message from the UI as it is not currently supported

Pull requests without a rationale and clear improvement may be closed
immediately.

### Notes
This removes the feature from the Qt GUI
Built and QA tested on Ubuntu 18.04 LTS

### BTC/BGL PR reward address
if applicable, please type your reward wallet address here

### CODE REVIEW

**Comment by naftalimurgor** [comment]
Hi @wu-emma 

Pleae Check this out
gitcoin address: `0x254A38f3d0ac5c1CFA923f3dD5029fE1fC4F45B1`

**Comment by janus** [comment]
I will go through it within the week.

**Comment by naftalimurgor** [comment]
@janus
Awsome, thanks. 
Also,I have already submit a bounty on gitcoin, but can't submit multiple as gitcoin does not support multiple submissions. It is not possible to submit this too for https://gitcoin.co/issue/29030

**Comment by janus** [comment]
> @janus Awsome, thanks. Also,I have already submit a bounty on gitcoin, but can't submit multiple as gitcoin does not support multiple submissions. It is not possible to submit this too for https://gitcoin.co/issue/29030

I am afraid what you removed is till in the current bitcoin master branch. I would like you to open an issue at bitcoin and point this out. If they accept your position, then I would merge your branch. 
Note that I just studied your code against bitcoin master. I have not tried to run and test your version yet. But I would be testing it out if your position is approved.

**Comment by van-orton** [comment]
I'll check this -- maybe it's worth a try, because new addresses do not support message signing. Unfortunately I don't think bitcoin repo maintainers would make this change :-) The relation with private key is through payment script for new addresses, which is not made for verification.

**Comment by wu-emma** [comment]
thanks for participation @naftalimurgor
0x252433424ce4a94e261f3ec89430b952256e118b7f022e1187e15b55dff5fcb4

**Comment by naftalimurgor** [comment]
@wu-emma 
Thanks a lot. I'll contribute more to help this project.

**Comment by 0xswakei** [comment]
> I'll check this -- maybe it's worth a try, because new addresses do not support message signing. Unfortunately I don't think bitcoin repo maintainers would make this change :-) The relation with private key is through payment script for new addresses, which is not made for verification.

Hey @van-orton 
Yeah, they most likely would never make that change.

**Pull request closed without merging**
