### PR TITLE
mempool_ * test updates and fixes

### PR DESCRIPTION
**Pull request by antonyip**
### Description
mempool_* test updates from bitcoin core

### Notes
Done for bounty @ https://gitcoin.co/issue/BitgesellOfficial/bitgesell/39/100026119
Before
image
After
image

### BTC/BGL PR reward address
0x0ba43bae4613e03492e4c17af3b014b6c3202b9d (ETH)

### CODE REVIEW

**Comment by van-orton** [comment]
Hi @antonyip! Nicely done, please give me 1-2 days more to merge it. Did you receive any payment for this PR through Gitcoin?

**Comment by antonyip** [comment]
Hello @van-orton,
Not for this PR.

**Comment by van-orton** [comment]
> Hello @van-orton,
> Not for this PR.

Got it, sorry for the delay, would sort it out

**Comment by wu-emma** [comment]
Hi @antonyip thanks for the contribution!
Please find the tx id https://etherscan.io/tx/0x0514dc4f99d4f00a7cdc535d688feca9cf601d57c0de0dc35e520d9c2206788d

**Pull request closed without merging**
