### PR TITLE
A few fixes on Qt wallets, new icons + fixes on some files, see description pls

### PR DESCRIPTION
**Pull request by le2Ks**
What's new in v0.1.3:
===

- dos2unix on files that were on wrong format
- chmod +x on depends
- fix on missing checkpoints infos + adding new checkpoint too
- fix on fpic error with hardening + jump to 0.1.3 + removing bench and test for compile

- **fix on seeds at chainparamsseeds.h, removing invalid dnsseeds that were set up for Bitcoin blockchain**

- already compiled depends for Windows x64 + x32 in source code at:    */bitgesell/depends/*    folder, see codes below to now compile Windows wallets on Linux 18.04:

To compile for Windows on Linux 18.04:
===

   - x64:
```
./autogen.sh && ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 && make -j$(nproc)
```
   - x32:
```
./autogen.sh && ./configure --prefix=`pwd`/depends/i686-w64-mingw32 && make -j$(nproc)
```

What's new in v0.1.4:
===

- Fix almost all missing icons in Qt version
- Edited some icons to match official Bitgesell theme color
- Fix on fallbackfee which was disabled by default and put a default value of 0.0001 instead
- New splashcreen, removed texts about version, names etc.. logo is now on transparent background - no window decoration
- Added logo in 64x64 format in readme

Screenshots:
===

<p align="center">
  
</p>

<p align="center">
  
</p>

<p align="center">
  
</p>

<p align="center">
  
</p>

<p align="center">
  
</p>

<p align="center">
  
</p>

<p align="center">
  
</p>

### CODE REVIEW

**Comment by Original-Tasty** [comment]
Please see description for more details

**Comment by van-orton** [comment]
I have checked the PR, and there's lots of good stuff here!
@Original-Tasty 
Just 2 small points:
- probably we should keep the DNS seeds in place (they are real and would be maintained);
- we recently made 'tools' folder (https://github.com/wu-emma/bitgesell/tree/master/tools), mb
  locate depends script there as 'tools/depends/depends.sh';

Otherwise I am ready to merge the PR. Let me know what you think. 
I also think we should add you as a maintainer with main repo access, would ask about it.

**Comment by le2Ks** [comment]
@van-orton 
Hi, so i've changed the files regarding what you said above.

The official dnsseeds are back to chainparams.cpp and the connection time delay is back to normal too.
i also removed the scripts i've provided before since you already had one

The only thing i didn't remove regarding the dns seeds is the file chainparamsseed.h, it is at the moment using the seeds from Bitcoin (BTC) blockchain.
Those are not mandatory since the wallet will actually auto connect to the dnsseeds from the chainparams.cpp file at first.
But if those are offline, the ones in chainparamsseeds.h are the ones the wallet will try to connect at in this situation. So it's important we have the correct  blockchain just in case.

Let me know what you think about this please!

The pull request is the same, but edited with the above modifications for what you asked me :) (instead of creating a new one, was easier to simply edit this one already there)

**Comment by van-orton** [comment]
Checked the changes, all looks good, merging this. Thanks! :+1:

**Pull request merged**
