### PR TITLE
Removing Error 1

### PR DESCRIPTION
**Pull request by ayushkumar63123**
The above code's syntax was wrong and error was being produced while testing. I corrected a line of code for removing the error.

### Description
To remove a syntax error for successful execution of the code.

Pull requests without a rationale and clear improvement may be closed
immediately.

GUI-related pull requests should be opened against
https://github.com/BGL-core/gui
first. See CONTRIBUTING.md
-->

### Notes
implementation details, hints for reviewers

### BTC/BGL PR reward address
1MqWcL1BtzJS4phxrxLFdooN911mBqQW1q

### CODE REVIEW

**Comment by ayushkumar63123** [comment]
Please use my TRX wallet address TZEhxuj58o4EDmeWnMfprEDkUBUVL3QwdY for rewarding instead of BTC address since BTC fee is higher.

**Comment by ayushkumar63123** [comment]
I have not been recognized yet for this sincere work of mine. I have also removed other errors in my forked repository bitgesell and have a successful build of the project. Please consider as soon as possible. I am still waiting.

**Comment by ayushkumar63123** [comment]
If my fixed work is not considered, this repository will remain erroneous. You can test the code of this repository using pytest and see the errors yourself. I am not doing timepass. I have the solution for the problems in my forked repository.

**Comment by ayushkumar63123** [comment]
I have made a pull request. Please merge it. If I get no reward, no problem. But I am glad to have solved syntax errors and would be satisfied if my PR of solved errors and successful build gets merged and errors removed from this repository.

**Comment by ayushkumar63123** [comment]
1 year no reply

**Comment by ayushkumar63123** [comment]
To remind i had fixed issues and made prs to solve errors in tests

**Comment by madnadyka** [comment]
This issue has been already solved with #53

**Pull request closed without merging**
