### PR TITLE
Fix bitcoinsync2022 branch build

### PR DESCRIPTION
**Pull request by gitcoindev**
### Description
Goal of this pull request is to fix bitcoinsync2022 branch build.

### Notes
When this PR will be merged the branch can be built with the usual commands

```
$  ./autogen.sh 
$  ./configure
$  make -j16
Making all in src

..

$ echo $?
0
```

### CODE REVIEW

**Comment by gitcoindev** [comment]
I did a clean checkout - this only fixes part of the problem as autogen.sh still fails with

```
configure.ac:1968: error: required file 'src/qt/Makefile' not found
configure.ac:1969: error: required file 'src/qt/test/Makefile' not found
configure.ac:1970: error: required file 'src/test/Makefile' not found
```

to be investigated.

**Comment by naftalimurgor** [comment]
Hey @gitcoindev 
This is really great, a pointer to that can be found on this issue comment: https://github.com/BitgesellOfficial/bitgesell/pull/125#issuecomment-1611947940
That would be really resourceful fixing the current failing build for this branch
Please check that out

**Comment by gitcoindev** [comment]
I have some more progress, cpp tests are building now, still QT part is broken due to linker error in locale, --with-gui=no passed to configure completes the build. QT part might be tricky but I will try to fix QT as well this week.

**Comment by janus** [comment]
> 
What do  you want to achieve here? 
And what is the purpose?

**Comment by gitcoindev** [comment]
Hi @janus! I would like to be able to build the full workspace from scratch on this branch as currently on master to be able to run and fix functional tests. I did use to build on Ubuntu using:

$ ./autogen.sh 
$  export BDB_PREFIX=`pwd`/db4
$  ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
$ make -j16

Now on bitcoinsync2022 branch the same build instructions fail, I was able to build using a few hacks, but this should work out of the box without any hacks as on master.

If this works for you, please let me know how you build clean workspace on this branch on Linux, perhaps I am missing something. Thank you!

**Comment by gitcoindev** [comment]
I was able to fix the remaining part - QT part was broken on this branch due to references to missing GUI locale (language translation files) for British English, Afrikaans and Hindi. The branch builds now. @janus if it did build for you, likely you might have a non-clean workspace with those files available but not pushed, hopefully it should be fine now.

**Comment by gitcoindev** [comment]
Hi @naftalimurgor it would be great if you tried out this branch as well and checked if it builds for you. If it goes for the locale files - I commented the references out in the last three commits, but the files do exist on the master branch. Therefore if translation is valid the missing files can be as well copied over from master.

**Comment by naftalimurgor** [comment]
Hi @gitcoindev 
Let me try out the build on Ubuntu 20.04 and 18.04 I've successful build master on these then provide feedback. Also, id copy over the missing files from master and rey building incase it fails to build

**Comment by gitcoindev** [comment]
Hi @naftalimurgor were you able to build the branch? If something is still broken i could try to help.

**Comment by naftalimurgor** [comment]
Hi @gitcoindev 

I am building that branch today, on Ubuntu 22.04 LTS then I'll get you the feedback about the outcome. Been busy with exams, my apologies for taking too long.

**Pull request closed without merging**
