### PR TITLE
Feature/functional test framework sync

### PR DESCRIPTION
**Pull request by gitcoindev**
Hi @janus this is the first batch update to sync branch, the previous one was from a wrong github account.

The PR contains fixes cherry-picked and merged from bitcoin@master and my fixes for wallet_labels.py and messages.py.

Next separate PR will be sync from bitcoin about timeout mockable and type safe, speed up test in util.py but it will also update src/rcp/net.cpp . It will fix a few failures as well.

I hope making smaller PRs will make it easier to review.

### CODE REVIEW

**Comment by gitcoindev** [comment]
Hi @janus the PR is targeting https://github.com/BitgesellOfficial/bitgesell/tree/janus/sync_31Oct2021 please let me know if this is fine. Please delete #77 as I cannot do this, was sent from a wrong account, thanks!

**Comment by janus** [comment]
> Hi @janus the PR is targeting https://github.com/BitgesellOfficial/bitgesell/tree/janus/sync_31Oct2021 please let me know if this is fine. Please delete #77 as I cannot do this, was sent from a wrong account, thanks!

Thanks for the update.  Target  sync_31Oct2021. But don't cherrypick that would see us go beyond 31st Oct 2021.

**Comment by gitcoindev** [comment]
> > Hi @janus the PR is targeting https://github.com/BitgesellOfficial/bitgesell/tree/janus/sync_31Oct2021 please let me know if this is fine. Please delete #77 as I cannot do this, was sent from a wrong account, thanks!
> 
> Thanks for the update. Target sync_31Oct2021. But don't cherrypick that would see us go beyond 31st Oct 2021.

Got it thanks, I just pushed a mock time integration from Bitcoin to Bitgesell but this is much beyond 31st Oct 2021, some commits are very recent. This fixes a few tests, speeds the tests as well, as instead of waiting with sleeps mocking time is now possible. You can have a look here:

https://github.com/BitgesellOfficial/bitgesell/compare/janus/sync_31Oct2021...gitcoindev:feature/test-p2p-timeout-mockable-sync?expand=1

I will not open a PR for this since I get now that you sync with Bitcoin to a given date, fix what is needed and release in BGL.

Since now I will try to compare test results to Bitcoin master @ 31Oct2021 then and fix strictly BGL related functional test errors.

**Comment by gitcoindev** [comment]
Just to confirm - I will now compare to Bitcoin at

2021-10-31 12:48:00 +0100 7986faf2e09ea85b1d4564ce910f07a4c4de8685 test: Fix segfault in the psbt_wallet_tests/psbt_updater_test

which is mentioned in the last sync log:

https://github.com/BitgesellOfficial/bitgesell/commit/bf15887c043368bf817404553e21f40417028a0c#diff-edaa616260fadc8c0508c3de2c296760e947ae1ece67f23232974307703e0b72R8807

**Pull request closed without merging**
